# -*- coding: utf-8 -*-
"""pizza-sales-data-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksFSlAS-PI4_6rOWsZzm-L6CdviQR6pM

# Pizza Sales Analysis
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

orders = pd.read_csv("orders.csv")
order_details = pd.read_csv("order_details.csv")
pizzas = pd.read_csv("pizzas.csv")
pizza_types = pd.read_csv("pizza_types.csv", encoding="latin1")

df = order_details.merge(orders, on="order_id")
df = df.merge(pizzas, on="pizza_id")
df = df.merge(pizza_types, on="pizza_type_id")

df["revenue"] = df["quantity"] * df["price"]

# Revenue by category
category_revenue = df.groupby("category")["revenue"].sum().sort_values(ascending=False)

plt.figure(figsize=(8, 5))
category_revenue.plot(kind="bar")
plt.title("Revenue by Pizza Category")
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.tight_layout()

# Create the 'images' directory if it doesn't exist
os.makedirs('images', exist_ok=True)

plt.savefig("images/revenue_by_category.png")
plt.show()

"""## Data Loading and Revenue by Category"""

df['date'] = pd.to_datetime(df['date'])
monthly_revenue = df.groupby(
    df['date'].dt.to_period('M')
)['revenue'].sum()
monthly_revenue.plot()

"""## Monthly Revenue Trend"""

daily_revenue = df.groupby('date')['revenue'].sum()
plt.plot(daily_revenue.index,
         daily_revenue.values)

"""## Daily Revenue Trend"""

category_revenue = (
    df.groupby('category')['revenue']
      .sum()
)
category_revenue.plot(kind='pie')

"""## Revenue Distribution by Category (Pie Chart)"""

size_sales = (
    df.groupby('size')['quantity']
      .sum()
)
size_sales.plot(kind='bar')

"""## Sales by Pizza Size"""

orders['hour'] = pd.to_datetime(
    orders['time']
).dt.hour

hourly_orders = (
    orders.groupby('hour')
          .size()
)
hourly_orders.plot(kind='bar')

"""## Hourly Order Distribution"""